- name: Kalliope World Wide time neuron
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: googlemaps
        version: 2.4.5
